import type {
  RFXEvent,
  ActiveEvent,
  SupplierResponse,
  Clarification,
  EvalCriterion,
  WizState,
} from "./rfx-types";

export const EVENTS_LIST: RFXEvent[] = [
  {
    id: 1,
    number: "RFT-2025-0018",
    type: "RFT",
    title: "Annual Decorative Lighting Contract - Phase 2",
    status: "UNDER_EVALUATION",
    deadline: "30 Sep 2025",
    responses: 5,
    qualified: 3,
  },
  {
    id: 2,
    number: "RFP-2025-0017",
    type: "RFP",
    title: "Office Furniture Procurement – HQ",
    status: "OPEN",
    deadline: "20 Oct 2025",
    responses: 2,
    qualified: 2,
  },
  {
    id: 3,
    number: "RFI-2025-0016",
    type: "RFI",
    title: "Market Survey: EV Charging Infrastructure",
    status: "PUBLISHED",
    deadline: "15 Oct 2025",
    responses: 0,
    qualified: 0,
  },
  {
    id: 4,
    number: "RFQ-DRAFT-001",
    type: "RFQ",
    title: "IT Hardware & Peripherals Refresh 2026",
    status: "DRAFT",
    deadline: "—",
    responses: 0,
    qualified: 0,
  },
  {
    id: 5,
    number: "RFT-DRAFT-002",
    type: "RFT",
    title: "Campus Security Infrastructure Upgrade",
    status: "DRAFT",
    deadline: "—",
    responses: 0,
    qualified: 0,
  },
];

export const ACTIVE_EVENT: ActiveEvent = {
  id: 1,
  number: "RFT-2025-0018",
  type: "RFT",
  title: "Annual Decorative Lighting Contract - Phase 2",
  status: "UNDER_EVALUATION",
  deadline: "30 Sep 2025",
  two_envelope: true,
  tech_opening: "05 Oct 2025",
  fin_opening: "15 Oct 2025",
  tech_phase: "OPENED",
  fin_phase: "SEALED",
  min_qual_score: 70,
};

export const RESPONSES: SupplierResponse[] = [
  {
    id: 1,
    supplier: "ABC Lighting Co.",
    country: "IN",
    submitted: "28 Sep 2025, 18:45",
    status: "SUBMITTED",
    tech_env: "OPENED",
    fin_env: "SEALED",
    tech_score: 84.5,
    fin_env_amount: null,
    rank: null,
    is_l1: false,
    is_disqualified: false,
    items: [
      { code: "LT-BRASS-001", desc: "Custom Brass Wall Sconce", qty: 500, unit: "PCS", unit_price: null, total: null },
      { code: "LT-LED-002", desc: "LED Retrofit Bulb 10W E27", qty: 2000, unit: "PCS", unit_price: null, total: null },
    ],
    answers: [
      { section: "Technical Compliance", q: "Upload Material Certification (IS 9900:2002)", type: "FILE_UPLOAD", val: "IS9900_ABC.pdf", score: null },
      { section: "Technical Compliance", q: "Warranty Period (months)", type: "NUMERIC", val: "24", score: 90 },
      { section: "Technical Compliance", q: "Manufacturing facility location", type: "SINGLE_CHOICE", val: "India (domestic)", score: 88 },
      { section: "Company Profile", q: "Years in business", type: "NUMERIC", val: "18", score: null },
      { section: "Company Profile", q: "ISO 9001:2015 Certified?", type: "BOOLEAN", val: "Yes", score: 100 },
    ],
  },
  {
    id: 2,
    supplier: "GlobeLux Industries",
    country: "DE",
    submitted: "29 Sep 2025, 11:20",
    status: "SUBMITTED",
    tech_env: "OPENED",
    fin_env: "SEALED",
    tech_score: 78.2,
    fin_env_amount: null,
    rank: null,
    is_l1: false,
    is_disqualified: false,
    items: [
      { code: "LT-BRASS-001", desc: "Custom Brass Wall Sconce", qty: 500, unit: "PCS", unit_price: null, total: null },
      { code: "LT-LED-002", desc: "LED Retrofit Bulb 10W E27", qty: 2000, unit: "PCS", unit_price: null, total: null },
    ],
    answers: [
      { section: "Technical Compliance", q: "Upload Material Certification", type: "FILE_UPLOAD", val: "Cert_GL.pdf", score: null },
      { section: "Technical Compliance", q: "Warranty Period (months)", type: "NUMERIC", val: "18", score: 75 },
      { section: "Technical Compliance", q: "Manufacturing facility location", type: "SINGLE_CHOICE", val: "Europe", score: 70 },
      { section: "Company Profile", q: "Years in business", type: "NUMERIC", val: "12", score: null },
      { section: "Company Profile", q: "ISO 9001:2015 Certified?", type: "BOOLEAN", val: "Yes", score: 100 },
    ],
  },
  {
    id: 3,
    supplier: "Nova Electricals Pvt Ltd",
    country: "IN",
    submitted: "30 Sep 2025, 22:55",
    status: "SUBMITTED",
    tech_env: "OPENED",
    fin_env: "SEALED",
    tech_score: 65.0,
    fin_env_amount: null,
    rank: null,
    is_l1: false,
    is_disqualified: true,
    disqualify_reason: "Technical score below minimum qualification threshold of 70.",
    items: [
      { code: "LT-BRASS-001", desc: "Custom Brass Wall Sconce", qty: 500, unit: "PCS", unit_price: null, total: null },
    ],
    answers: [
      { section: "Technical Compliance", q: "Upload Material Certification", type: "FILE_UPLOAD", val: null, score: null },
      { section: "Technical Compliance", q: "Warranty Period (months)", type: "NUMERIC", val: "12", score: 55 },
      { section: "Company Profile", q: "ISO 9001:2015 Certified?", type: "BOOLEAN", val: "No", score: 0 },
    ],
  },
  {
    id: 4,
    supplier: "LightWave Solutions",
    country: "SG",
    submitted: "—",
    status: "WITHDRAWN",
    tech_env: "SEALED",
    fin_env: "SEALED",
    tech_score: null,
    fin_env_amount: null,
    rank: null,
    is_l1: false,
    is_disqualified: false,
    items: [],
    answers: [],
  },
  {
    id: 5,
    supplier: "BrightPath GmbH",
    country: "DE",
    submitted: "30 Sep 2025, 09:10",
    status: "SUBMITTED",
    tech_env: "OPENED",
    fin_env: "SEALED",
    tech_score: 81.0,
    fin_env_amount: null,
    rank: null,
    is_l1: false,
    is_disqualified: false,
    items: [
      { code: "LT-BRASS-001", desc: "Custom Brass Wall Sconce", qty: 500, unit: "PCS", unit_price: null, total: null },
      { code: "LT-LED-002", desc: "LED Retrofit Bulb 10W E27", qty: 2000, unit: "PCS", unit_price: null, total: null },
    ],
    answers: [
      { section: "Technical Compliance", q: "Warranty Period (months)", type: "NUMERIC", val: "24", score: 88 },
      { section: "Company Profile", q: "ISO 9001:2015 Certified?", type: "BOOLEAN", val: "Yes", score: 100 },
    ],
  },
];

export const CRITERIA: EvalCriterion[] = [
  { name: "Prior Project Experience", type: "TECHNICAL", weight: 25, max: 100, is_pf: false },
  { name: "Technical Team Strength", type: "TECHNICAL", weight: 20, max: 100, is_pf: false },
  { name: "Quality & Compliance Certifications", type: "COMPLIANCE", weight: 15, max: 100, is_pf: false },
  { name: "Financial Turnover ≥ ₹2Cr", type: "FINANCIAL", weight: 0, max: 0, is_pf: true },
  { name: "Warranty Period", type: "TECHNICAL", weight: 15, max: 100, is_pf: false },
  { name: "Manufacturing Location", type: "TECHNICAL", weight: 10, max: 100, is_pf: false },
  { name: "ISO Certifications", type: "COMPLIANCE", weight: 15, max: 100, is_pf: false },
];

export const CLARIFICATIONS: Clarification[] = [
  {
    id: 1,
    q: "Please clarify whether IP44 rating is mandatory for indoor wall sconces installed in dry locations.",
    a: "IP44 rating is mandatory for all installations regardless of location as per project specification clause 3.2.1.",
    asked: "25 Aug 2025",
    answered: "26 Aug 2025",
    supplier: "ABC Lighting Co.",
    anon: true,
    published: true,
    status: "ANSWERED",
  },
  {
    id: 2,
    q: "Can we offer equivalent products if the specified model is out of stock?",
    a: "Equivalent products are acceptable provided they meet all technical specifications. Please clearly state deviations in the deviation_notes field.",
    asked: "28 Aug 2025",
    answered: "29 Aug 2025",
    supplier: "GlobeLux Industries",
    anon: false,
    published: true,
    status: "ANSWERED",
  },
  {
    id: 3,
    q: "Is the site visit on 20 Aug mandatory or optional for foreign bidders?",
    a: null,
    asked: "10 Aug 2025",
    answered: null,
    supplier: "GlobeLux Industries",
    anon: false,
    published: false,
    status: "PENDING",
  },
  {
    id: 4,
    q: "Please confirm if the BIS certification under IS 9900 is mandatory or if equivalent international certification is acceptable.",
    a: null,
    asked: "12 Aug 2025",
    answered: null,
    supplier: "Nova Electricals",
    anon: true,
    published: false,
    status: "PENDING",
  },
];

export const SUPPLIER_CATALOGUE = [
  { name: "Zenith Electricals", country: "IN" },
  { name: "BrightPath GmbH", country: "DE" },
  { name: "Voltex Solutions", country: "US" },
  { name: "IndoLux Pvt Ltd", country: "IN" },
  { name: "EuroLight AG", country: "CH" },
  { name: "Prism Electricals", country: "IN" },
  { name: "TechnoFab Industries", country: "IN" },
  { name: "Luminary Corp", country: "SG" },
  { name: "Pacific Wiring Ltd", country: "AU" },
  { name: "AlphaVolt GmbH", country: "DE" },
];

export const DEFAULT_WIZ_STATE: WizState = {
  step: 0,
  type: "RFT",
  toggles: {
    nda_required: true,
    intent_to_participate_req: true,
    allow_supplier_attachments: true,
    two_envelope_system: true,
    bid_bond_required: true,
    site_visit_required: false,
    price_negotiation_enabled: false,
  },
  items: [
    { id: 1, item_code: "LT-BRASS-001", description: "Custom Brass Wall Sconce", quantity: "500", unit: "PCS", target_price: "1200.00", technical_spec: "Brass finish, E27, IP44", required_by: "2026-01-15" },
    { id: 2, item_code: "LT-LED-002", description: "LED Retrofit Bulb 10W E27", quantity: "2000", unit: "PCS", target_price: "180.00", technical_spec: "10W, E27 base, 4000K", required_by: "2026-01-20" },
  ],
  sections: [
    {
      id: 1, title: "Technical Compliance", type: "TECHNICAL", mandatory: true,
      questions: [
        { id: 1, text: "Upload Material Certification (IS 9900:2002)", qtype: "FILE_UPLOAD", mandatory: true, scored: false },
        { id: 2, text: "Warranty Period (months)", qtype: "NUMERIC", mandatory: true, scored: true, weight: 15 },
        { id: 3, text: "Manufacturing facility location", qtype: "SINGLE_CHOICE", mandatory: true, scored: true, weight: 10, options: ["India", "China", "Europe", "Other"] },
      ],
    },
    {
      id: 2, title: "Company Profile", type: "GENERAL", mandatory: true,
      questions: [
        { id: 4, text: "Years in business", qtype: "NUMERIC", mandatory: true, scored: false },
        { id: 5, text: "ISO 9001:2015 Certified?", qtype: "BOOLEAN", mandatory: true, scored: true, weight: 8 },
      ],
    },
  ],
  participants: [
    { id: 1, name: "ABC Lighting Co.", country: "IN", status: "SUBMITTED" },
    { id: 2, name: "GlobeLux Industries", country: "DE", status: "ACCEPTED" },
    { id: 3, name: "Nova Electricals", country: "IN", status: "INVITED" },
    { id: 4, name: "LightWave Solutions", country: "SG", status: "DECLINED" },
  ],
  reminders: [
    { id: 1, headline: "Submission Deadline – 48h remaining", scheduled: "28 Sep 2025, 09:00", recipients: ["SUPPLIER"], sent: false, excl_sub: true },
    { id: 2, headline: "Clarification deadline tomorrow", scheduled: "14 Sep 2025, 09:00", recipients: ["SUPPLIER", "MANAGER"], sent: true, excl_sub: false },
  ],
  _inviteOpen: false,
  _inviteSearch: "",
  _inviteSelected: [],
};

export const TYPE_CONFIG = {
  RFI: {
    color: "#6366f1", bg: "#eef2ff", name: "Request for Information", tagline: "Market research – no pricing collected",
    steps: ["Event type", "Basic details", "Documents", "Questionnaire", "Participants", "Reminders", "Review"],
    stepSubs: ["RFI / RFP / RFQ / RFT", "Title, dates, settings", "Specs & NDA", "Qualification questions", "Invite suppliers", "Schedule reminders", "Final check"],
    showItems: false, showPricing: false, showBidBond: false, showTwoEnvelope: false, showSiteVisit: false, showTechFields: false, showEvalCriteria: false,
    togglesToShow: ["nda_required", "intent_to_participate_req", "allow_supplier_attachments", "price_negotiation_enabled"],
    infoBox: "RFI collects qualitative information only. No BOQ, no pricing, no bid bond. Questionnaire is the primary response mechanism.",
  },
  RFP: {
    color: "#0ea5e9", bg: "#e0f2fe", name: "Request for Proposal", tagline: "Proposals with pricing & methodology – weighted evaluation",
    steps: ["Event type", "Basic details", "Deliverables", "Documents", "Questionnaire", "Participants", "Reminders", "Review"],
    stepSubs: ["RFI / RFP / RFQ / RFT", "Title, dates, settings", "Optional scope items", "Specs & T&Cs", "Evaluation questions", "Invite suppliers", "Schedule reminders", "Final check"],
    showItems: true, showPricing: true, showBidBond: false, showTwoEnvelope: false, showSiteVisit: false, showTechFields: false, showEvalCriteria: true,
    itemsLabel: "Deliverables / scope items",
    itemsNote: "Deliverables are optional for RFP. Add items to request line-level pricing.",
    togglesToShow: ["nda_required", "intent_to_participate_req", "allow_supplier_attachments", "price_negotiation_enabled"],
    infoBox: "RFP collects detailed proposals with pricing, methodology, and team qualifications. Award is based on weighted technical + commercial score.",
  },
  RFQ: {
    color: "#f59e0b", bg: "#fef3c7", name: "Request for Quotation", tagline: "Competitive price comparison – BOQ mandatory",
    steps: ["Event type", "Basic details", "Line items (BOQ)", "Documents", "Questionnaire", "Participants", "Reminders", "Review"],
    stepSubs: ["RFI / RFP / RFQ / RFT", "Title, dates, settings", "Mandatory BOQ & quantities", "Specs & T&Cs", "Optional questions", "Invite suppliers", "Schedule reminders", "Final check"],
    showItems: true, showPricing: true, showBidBond: true, showTwoEnvelope: false, showSiteVisit: false, showTechFields: false, showEvalCriteria: false,
    itemsLabel: "Line items / Bill of Quantities",
    itemsNote: "Line items are mandatory for RFQ. Suppliers will price each line.",
    togglesToShow: ["nda_required", "allow_supplier_attachments", "bid_bond_required", "price_negotiation_enabled"],
    infoBox: "RFQ requires a complete BOQ. Suppliers submit sealed unit prices per line item. Award goes to the L1 (lowest qualified price).",
  },
  RFT: {
    color: "#0d9488", bg: "#f0fdfa", name: "Request for Tender", tagline: "Formal two-envelope tender – technical gate + financial bid",
    steps: ["Event type", "Basic details", "BOQ / Schedule", "Documents", "Questionnaire", "Participants", "Reminders", "Review"],
    stepSubs: ["RFI / RFP / RFQ / RFT", "Title, dates & compliance", "Mandatory BOQ + specs", "Specs, NDA & T&Cs", "Technical qualification", "Invite suppliers", "Schedule reminders", "Final check"],
    showItems: true, showPricing: true, showBidBond: true, showTwoEnvelope: true, showSiteVisit: true, showTechFields: true, showEvalCriteria: true,
    itemsLabel: "BOQ / Schedule of rates",
    itemsNote: "BOQ is mandatory for RFT. Each item must have item code, quantity, unit, and technical specification.",
    togglesToShow: ["nda_required", "intent_to_participate_req", "allow_supplier_attachments", "two_envelope_system", "bid_bond_required", "site_visit_required", "price_negotiation_enabled"],
    infoBox: "RFT uses a two-envelope system: technical bids are evaluated before financial bids are opened. Only technically qualified suppliers advance to the financial stage.",
  },
} as const;
